name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: [bug]
assignees:
  - GrayGalaxy
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the [Code of Conduct](/graygalaxy/windows-uup/blob/main/.github/code_of_conduct.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](/graygalaxy/windows-uup/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Tell us what you observed...

        - Browser: Chrome / MS Edge / Safari ...
    validations:
      required: true
  - type: input
    attributes:
      label: Relevent URL
      description: Provide the url where the error occoured
      placeholder: /download
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant console output (optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    attributes:
      label: Reproduction steps (optional)
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      placeholder: |
        1.
        2.
        3. ...
